### ISSUE TITLE
请问一下关于该小程序真机调试

### ISSUE THREAD

**Issue by hfq-xiajianglong** [TencentVideoCloudMLVBDev/MiniProgram#1]
必须先开通实时播放/录制音视频流的接口吗？
![image](https://user-images.githubusercontent.com/37646269/40339563-a3f43c40-5dad-11e8-97ff-df3545bc196e.png)

**Comment by suonian** [comment]
是的，只有开通了才可以使用 <live-pusher> 和 <live-player> 两个标签
https://cloud.tencent.com/document/product/454/12517#.E5.A6.82.E4.BD.95.E5.BC.80.E9.80.9A

**Comment by carolsuo** [comment]
是的，只有开通了才可以使用 live-pusher 和  live-player 两个标签
https://cloud.tencent.com/document/product/454/12517#.E5.A6.82.E4.BD.95.E5.BC.80.E9.80.9A
